### ISSUE TITLE
[SENTINEL] Sentinel Reliability Improvements

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/superfluid-sentinel#301]
A collection of:

## Desired Improvement Items

- [ ] Have more visibility/relations of opt-in sentinels:
  - Pick up where we stopped re prometheus integration. 
  - Being able to tag superfluid-hosted sentinels.
  - Being able to provide contact information to us for better support.
- [ ] Support 1559 tx type.
- [ ] Automation for snapshot system.
- [ ] Revisit token selection logic documentation & communication.
